// itch/tests/test_itch.cpp — golden-vector and malformed-corpus suite for the
// ITCH 5.0 decoder. RED: these tests must FAIL before the decoder exists and
// must PASS only when every field matches the spec-derived golden vectors.
#include <afx/test_framework.hpp>

#include <cstdint>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <map>
#include <sstream>
#include <string>
#include <vector>

#include <itch/itch_codec.hpp>

namespace fs = std::filesystem;

static std::string g_root;  // cpp/ root, set from argv[1]

static std::string read_file(const fs::path& p) {
    std::ifstream in(p, std::ios::binary);
    std::ostringstream ss;
    ss << in.rdbuf();
    return ss.str();
}

static std::vector<uint8_t> read_bin(const fs::path& p) {
    std::ifstream in(p, std::ios::binary);
    return {std::istreambuf_iterator<char>(in), std::istreambuf_iterator<char>()};
}

// Parse "key=value" lines (skipping "#" comments) into a map.
static std::map<std::string, std::string> parse_expect(const std::string& text) {
    std::map<std::string, std::string> out;
    std::istringstream ss(text);
    std::string line;
    while (std::getline(ss, line)) {
        if (line.empty() || line[0] == '#') continue;
        auto eq = line.find('=');
        if (eq == std::string::npos) continue;
        out[line.substr(0, eq)] = line.substr(eq + 1);
    }
    return out;
}

// Render a decoded message as a key->value string map, mirroring the golden
// .expect keys generated by itch/tools/make_itch_golden.py.
static std::map<std::string, std::string> to_field_map(const itch::Decoded& d) {
    std::map<std::string, std::string> m;
    m["type"] = itch::to_string(d.type);
    auto common = [&m](const itch::CommonHeader& h) {
        m["locate"] = std::to_string(h.stock_locate);
        m["tracking"] = std::to_string(h.tracking_number);
        m["timestamp_ns"] = std::to_string(h.timestamp_ns);
    };
    std::visit(
        [&](const auto& p) {
            using T = std::decay_t<decltype(p)>;
            if constexpr (std::is_same_v<T, itch::SystemEvent>) {
                common(p.hdr);
                m["event_code"] = std::string(1, p.event_code);
            } else if constexpr (std::is_same_v<T, itch::StockDirectory>) {
                common(p.hdr);
                m["stock"] = p.stock;
                m["market_category"] = std::string(1, p.market_category);
                m["financial_status"] = std::string(1, p.financial_status);
                m["round_lot_size"] = std::to_string(p.round_lot_size);
                m["round_lots_only"] = std::string(1, p.round_lots_only);
                m["issue_classification"] = std::string(1, p.issue_classification);
                m["issue_sub_type"] = p.issue_sub_type;
                m["authenticity"] = std::string(1, p.authenticity);
                m["short_sale_threshold"] = std::string(1, p.short_sale_threshold);
                m["ipo_flag"] = std::string(1, p.ipo_flag);
                m["luld_reference_price_tier"] =
                    std::string(1, p.luld_reference_price_tier);
                m["etp_flag"] = std::string(1, p.etp_flag);
                m["etp_leverage_factor"] = std::to_string(p.etp_leverage_factor);
                m["inverse_indicator"] = std::string(1, p.inverse_indicator);
            } else if constexpr (std::is_same_v<T, itch::StockTradingAction>) {
                common(p.hdr);
                m["stock"] = p.stock;
                m["trading_state"] = std::string(1, p.trading_state);
                m["reason"] = p.reason;
            } else if constexpr (std::is_same_v<T, itch::AddOrder>) {
                common(p.hdr);
                m["order_ref"] = std::to_string(p.order_ref);
                m["side"] = std::string(1, p.side);
                m["shares"] = std::to_string(p.shares);
                m["stock"] = p.stock;
                m["price"] = std::to_string(p.price);
                if (p.has_attribution) m["attribution"] = p.attribution;
            } else if constexpr (std::is_same_v<T, itch::OrderExecuted>) {
                common(p.hdr);
                m["order_ref"] = std::to_string(p.order_ref);
                m["executed_shares"] = std::to_string(p.executed_shares);
                m["match_number"] = std::to_string(p.match_number);
                if (p.has_price) {
                    m["printable"] = std::string(1, p.printable);
                    m["price"] = std::to_string(p.price);
                }
            } else if constexpr (std::is_same_v<T, itch::OrderCancel>) {
                common(p.hdr);
                m["order_ref"] = std::to_string(p.order_ref);
                m["cancelled_shares"] = std::to_string(p.cancelled_shares);
            } else if constexpr (std::is_same_v<T, itch::OrderDelete>) {
                common(p.hdr);
                m["order_ref"] = std::to_string(p.order_ref);
            } else if constexpr (std::is_same_v<T, itch::OrderReplace>) {
                common(p.hdr);
                m["original_order_ref"] = std::to_string(p.original_order_ref);
                m["new_order_ref"] = std::to_string(p.new_order_ref);
                m["shares"] = std::to_string(p.shares);
                m["price"] = std::to_string(p.price);
            } else if constexpr (std::is_same_v<T, itch::TradeNonCross>) {
                common(p.hdr);
                m["order_ref"] = std::to_string(p.order_ref);
                m["side"] = std::string(1, p.side);
                m["shares"] = std::to_string(p.shares);
                m["stock"] = p.stock;
                m["price"] = std::to_string(p.price);
                m["match_number"] = std::to_string(p.match_number);
            } else if constexpr (std::is_same_v<T, itch::CrossTrade>) {
                common(p.hdr);
                m["shares"] = std::to_string(p.shares);
                m["stock"] = p.stock;
                m["cross_price"] = std::to_string(p.cross_price);
                m["match_number"] = std::to_string(p.match_number);
                m["cross_type"] = std::string(1, p.cross_type);
            } else if constexpr (std::is_same_v<T, itch::BrokenTrade>) {
                common(p.hdr);
                m["match_number"] = std::to_string(p.match_number);
            }
        },
        d.payload);
    return m;
}

// Every golden vector decodes Ok and every field matches the spec-derived
// expectation exactly.
AFX_TEST(golden_vectors_decode_exactly) {
    fs::path dir = fs::path(g_root) / "itch" / "golden";
    int checked = 0;
    for (const auto& e : fs::directory_iterator(dir)) {
        if (e.path().extension() != ".bin") continue;
        fs::path expect_path = e.path();
        expect_path.replace_extension(".expect");
        AFX_EXPECT(fs::exists(expect_path));

        auto bytes = read_bin(e.path());
        auto expect = parse_expect(read_file(expect_path));
        AFX_EXPECT(!bytes.empty());

        itch::Decoded out;
        itch::DecodeStatus st = itch::decode(bytes.data(), bytes.size(), out);
        if (st != itch::DecodeStatus::Ok) {
            AFX_EXPECT_EQ((int)st, (int)itch::DecodeStatus::Ok);
            continue;
        }

        // Wire length check: the spec tables define fixed lengths; the
        // decoder must report the same length the generator encoded.
        size_t wire = 0;
        auto it = expect.find("# wire_len");
        (void)it;
        // The '# wire_len' comment is stripped by parse_expect; re-derive from
        // the actual buffer size instead:
        wire = bytes.size();
        AFX_EXPECT_EQ(itch::wire_length(out.type), wire);

        auto got = to_field_map(out);
        for (const auto& [k, v] : expect) {
            if (k.empty() || k[0] == '#') continue;
            if (got.find(k) == got.end()) {
                AFX_EXPECT_STREQ(std::string("<missing field> ") + k,
                                 std::string("present"));
                continue;
            }
            if (got[k] != v) {
                std::string msg = std::string("field ") + k + " of " +
                                  e.path().filename().string();
                AFX_EXPECT_STREQ(got[k], v);
                (void)msg;
            }
        }
        ++checked;
    }
    AFX_EXPECT(checked >= 15);  // the generator emits 15+ vectors
}

// Every malformed vector is rejected with its exact typed status and the
// output object stays untouched; no crash.
AFX_TEST(malformed_corpus_rejected_without_crash) {
    fs::path dir = fs::path(g_root) / "itch" / "malformed";
    int checked = 0;
    for (const auto& e : fs::directory_iterator(dir)) {
        if (e.path().extension() != ".bin") continue;
        fs::path expect_path = e.path();
        expect_path.replace_extension(".expect");
        auto expect = parse_expect(read_file(expect_path));
        auto bytes = read_bin(e.path());

        itch::Decoded out;
        out.type = itch::MessageType::SystemEvent;
        out.payload = itch::SystemEvent{{0xFFFF, 0xFFFF, 0xFFFFFFFFFFFFFFull}, 'Q'};
        itch::DecodeStatus st = itch::decode(bytes.data(), bytes.size(), out);

        const std::string want = expect["status"];
        std::string got = itch::to_string(st);
        if (got != want) {
            std::string msg = e.path().filename().string() + ": want " + want +
                              ", got " + got;
            AFX_EXPECT_STREQ(got, want);
            (void)msg;
        } else {
            // Output must be untouched on rejection.
            const auto* se = std::get_if<itch::SystemEvent>(&out.payload);
            AFX_EXPECT(se != nullptr);
            if (se) {
                AFX_EXPECT_EQ(se->hdr.stock_locate, 0xFFFF);
                AFX_EXPECT_EQ(se->hdr.tracking_number, 0xFFFF);
                AFX_EXPECT_EQ(se->event_code, 'Q');
            }
        }
        ++checked;
    }
    AFX_EXPECT(checked >= 6);
}

// Robustness: random single-byte mutations of a valid golden message never
// crash the decoder; when decode reports Ok the result must round-trip
// through the field map without throwing.
AFX_TEST(random_mutations_never_crash) {
    fs::path add_path = fs::path(g_root) / "itch" / "golden" / "add_order_buy.bin";
    auto base = read_bin(add_path);
    AFX_EXPECT_EQ(base.size(), (size_t)36);

    uint32_t state = 0x12345678u;
    auto next = [&state]() {
        state ^= state << 13;
        state ^= state >> 17;
        state ^= state << 5;
        return state;
    };
    for (int i = 0; i < 200000; ++i) {
        std::vector<uint8_t> buf = base;
        buf[next() % buf.size()] ^= (uint8_t)(1u << (next() % 8));
        itch::Decoded out;
        itch::DecodeStatus st = itch::decode(buf.data(), buf.size(), out);
        if (st == itch::DecodeStatus::Ok) {
            auto m = to_field_map(out);  // must not throw
            (void)m;
        }
    }
}

// Explicit big-endian / fixed-point checks from spec "Data Types" (page 4).
AFX_TEST(explicit_endian_and_fixed_point) {
    fs::path p = fs::path(g_root) / "itch" / "golden" / "add_order_buy.bin";
    auto bytes = read_bin(p);
    itch::Decoded out;
    AFX_EXPECT(itch::decode(bytes.data(), bytes.size(), out) == itch::DecodeStatus::Ok);
    const auto* add = std::get_if<itch::AddOrder>(&out.payload);
    AFX_EXPECT(add != nullptr);
    if (!add) return;
    // price 4800.0000 => 48,000,000 fixed-point integer
    AFX_EXPECT_EQ(add->price, 48000000u);
    // timestamp 9:30:00.000123456 => 34,200,000,123,456 ns
    AFX_EXPECT_EQ(add->hdr.timestamp_ns, 34200000123456ull);
    // locate 3000 => 0x0BB8 read big-endian
    AFX_EXPECT_EQ(add->hdr.stock_locate, 3000u);
    AFX_EXPECT_EQ(add->shares, 100u);
    AFX_EXPECT_STREQ(add->stock, std::string("AAPL"));
    AFX_EXPECT_EQ(add->side, 'B');
    AFX_EXPECT(!add->has_attribution);
}

// The spec maximum price 200,000.0000 (0x77359400) decodes Ok; one unit above
// is rejected (see malformed corpus too).
AFX_TEST(max_price_boundary) {
    fs::path p = fs::path(g_root) / "itch" / "golden" / "add_order_max_price.bin";
    auto bytes = read_bin(p);
    itch::Decoded out;
    AFX_EXPECT(itch::decode(bytes.data(), bytes.size(), out) == itch::DecodeStatus::Ok);
    const auto* add = std::get_if<itch::AddOrder>(&out.payload);
    AFX_EXPECT(add != nullptr);
    if (add) AFX_EXPECT_EQ(add->price, 2000000000u);
}

int main(int argc, char** argv) {
    g_root = (argc > 1) ? argv[1] : ".";
    return afx::run_all(argc, argv);
}
