"""Latency probe: measured one-way delay between this host and Binance Spot.

DIRECTORY: NEW (latency-probe-20260918/). Does NOT touch the productive
service, XERJ or any frozen artifact: it opens its own independent public
connections and writes only inside this directory.

Method (declared, honest):
  1. Clock-offset estimation against the venue: REST GET /api/v3/time
     (pinned in BINANCE_SOURCE_LOCK.md rest-api.md, SHA256 49EA6809…):
     offset_i = server_time_ms - (t_send_local + RTT_i/2). Median over N=12
     samples; uncertainty = ±median_RTT/2.
  2. Public market streams (pinned web-socket-streams.md, SHA256 32BF73A0…):
     /stream?streams=btcusdt@depth@100ms/btcusdt@trade on
     stream.binance.com:9443. Ping frames are answered with pong (spec).
     Per message: one_way_delay_ms = t_recv_local - (E_event_time_ms + offset).
     E = event time generated by the venue (spec field).
  3. WS ping/pong RTT measured separately (no clock needed): median of N.
  4. Outputs report.json + REPORT.md; p50/p99/mean/max computed on the real
     samples. Nothing estimated.

Duration: ~180 s (depth cadence 100 ms -> ~1800 samples; trades variable).
"""
from __future__ import annotations

import asyncio
import json
import pathlib
import statistics
import sys
import time
import urllib.request

import websockets

HERE = pathlib.Path(__file__).resolve().parent
DURATION_S = 180
REST_SAMPLES = 12


def pct(xs: list[float], p: float) -> float:
    xs = sorted(xs)
    idx = int(p * (len(xs) - 1) + 0.5)
    return xs[idx]


def measure_offset() -> tuple[float, float]:
    """REST /api/v3/time offset; returns (median_offset_ms, median_rtt_ms)."""
    offsets: list[float] = []
    rtts: list[float] = []
    url = "https://api.binance.com/api/v3/time"
    for _ in range(REST_SAMPLES):
        t0_wall = time.time() * 1000.0  # wall clock, ms
        t0_perf = time.perf_counter()
        with urllib.request.urlopen(url, timeout=10) as resp:
            server_ms = json.loads(resp.read())["serverTime"]
        t1_perf = time.perf_counter()
        rtt_ms = (t1_perf - t0_perf) * 1000.0
        # Local wall clock vs venue clock: assume symmetric path (documented).
        offset = server_ms - t0_wall - rtt_ms / 2.0
        offsets.append(offset)
        rtts.append(rtt_ms)
    return statistics.median(offsets), statistics.median(rtts)


async def main() -> int:
    print("== measuring REST clock offset ==")
    offset_ms, rtt_ms = measure_offset()
    print(f"offset_median_ms={offset_ms:.2f}  rest_rtt_median_ms={rtt_ms:.2f}")

    url = "wss://stream.binance.com:9443/stream?streams=btcusdt@depth@100ms/btcusdt@trade"
    depth: list[float] = []
    trade: list[float] = []
    depth_gaps: list[float] = []
    trade_gaps: list[float] = []
    last_depth_recv = None
    last_trade_recv = None
    ws_rtts: list[float] = []
    ping_epoch = 0

    t_start = time.perf_counter()
    ws_rtts: list[float] = []
    print(f"== opening {url} for {DURATION_S}s (pure receive, no stalls) ==")
    async with websockets.connect(url, ping_interval=None, max_size=2**22) as ws:
        while time.perf_counter() - t_start < DURATION_S:
            try:
                raw = await asyncio.wait_for(ws.recv(), timeout=20)
            except asyncio.TimeoutError:
                print("recv timeout (no data for 20s)")
                break
            t_recv = time.perf_counter()       # monotonic (inter-arrival)
            t_wall = time.time() * 1000.0      # wall clock (delay vs venue)
            # Market data arrives as TEXT frames (JSON); control frames
            # (pong/subscription acks) are filtered by stream/type below.
            try:
                doc = json.loads(raw) if isinstance(raw, str) else json.loads(raw.decode())
            except Exception:
                continue
            if isinstance(doc, dict) and "stream" in doc:
                stream = doc["stream"]
                data = doc.get("data", {})
            else:
                stream = doc.get("e", "")
                data = doc
            E = data.get("E")
            if not isinstance(E, (int, float)):
                continue
            one_way = t_wall - (E + offset_ms)
            if stream.endswith("@depth@100ms"):
                depth.append(one_way)
                if last_depth_recv is not None:
                    depth_gaps.append(t_recv - last_depth_recv)
                last_depth_recv = t_recv
            elif stream.endswith("@trade"):
                trade.append(one_way)
                if last_trade_recv is not None:
                    trade_gaps.append(t_recv - last_trade_recv)
                last_trade_recv = t_recv

        # RTT phase AFTER data collection: no per-message stats are touched,
        # so ping stalls cannot contaminate the delay distribution.
        print("== WS ping/pong RTT phase (12 samples) ==")
        for _ in range(12):
            t0 = time.perf_counter()
            try:
                pong_waiter = await ws.ping()
                await asyncio.wait_for(pong_waiter, timeout=10)
                ws_rtts.append((time.perf_counter() - t0) * 1000.0)
            except Exception:
                pass

    print(f"depth samples={len(depth)}  trade samples={len(trade)}  ws_rtts={len(ws_rtts)}")
    report = {
        "generated_utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "method": (
            "one_way_delay_ms = local_receive_time - (venue_event_time_E_ms + "
            "median_clock_offset); offset via GET /api/v3/time x12; "
            "uncertainty = +/- median_REST_RTT/2. WS ping/pong RTT is "
            "clock-free (no offset involved)."
        ),
        "spec_pins": {
            "web_socket_streams_md_sha256": "32bf73a0bed3b75e3ca981fdbaf48c53544bbdfb5944ef8ed1c4d7af9aceba0a",
            "rest_api_md_sha256": "49ea6809243fc7fb426e07f2fe662097736c7bb405bd2da5eef637d715427999",
        },
        "clock": {
            "offset_median_ms": offset_ms,
            "rest_rtt_median_ms": rtt_ms,
            "uncertainty_ms": rtt_ms / 2.0,
        },
        "ws_ping_pong_rtt_ms": {
            "samples": len(ws_rtts),
            "p50": pct(ws_rtts, 0.50) if ws_rtts else None,
            "p99": pct(ws_rtts, 0.99) if ws_rtts else None,
            "mean": statistics.mean(ws_rtts) if ws_rtts else None,
            "max": max(ws_rtts) if ws_rtts else None,
        },
        "duration_s": DURATION_S,
        "depth_btcusdt_100ms": {
            "samples": len(depth),
            "one_way_ms_p50": pct(depth, 0.50) if depth else None,
            "one_way_ms_p99": pct(depth, 0.99) if depth else None,
            "one_way_ms_mean": statistics.mean(depth) if depth else None,
            "one_way_ms_max": max(depth) if depth else None,
            "inter_arrival_s_p50": pct(depth_gaps, 0.50) if depth_gaps else None,
            "inter_arrival_s_p99": pct(depth_gaps, 0.99) if depth_gaps else None,
        },
        "trade_btcusdt": {
            "samples": len(trade),
            "one_way_ms_p50": pct(trade, 0.50) if trade else None,
            "one_way_ms_p99": pct(trade, 0.99) if trade else None,
            "one_way_ms_mean": statistics.mean(trade) if trade else None,
            "one_way_ms_max": max(trade) if trade else None,
            "inter_arrival_s_p50": pct(trade_gaps, 0.50) if trade_gaps else None,
            "inter_arrival_s_p99": pct(trade_gaps, 0.99) if trade_gaps else None,
        },
        "notes": [
            "measured on this host, one independent public connection",
            "does not touch the productive 24h soak service",
            "E is the venue event time (ms) per the pinned spec",
        ],
    }
    (HERE / "report.json").write_text(json.dumps(report, indent=2) + "\n")
    print(json.dumps(report, indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(asyncio.run(main()))
